//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Resources.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure.
        /// </summary>
        public static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://azure.microsoft.com/en-us/.
        /// </summary>
        public static string AzureLink {
            get {
                return ResourceManager.GetString("AzureLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor WebAssembly.
        /// </summary>
        public static string BlazorWebAssembly {
            get {
                return ResourceManager.GetString("BlazorWebAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor.
        /// </summary>
        public static string BlazorWebAssemblyLink {
            get {
                return ResourceManager.GetString("BlazorWebAssemblyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap.
        /// </summary>
        public static string Bootstrap {
            get {
                return ResourceManager.GetString("Bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://getbootstrap.com.
        /// </summary>
        public static string BootstrapLink {
            get {
                return ResourceManager.GetString("BootstrapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit.
        /// </summary>
        public static string Circuit {
            get {
                return ResourceManager.GetString("Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reffi.
        /// </summary>
        public static string CircuitDrawingCreditArtist {
            get {
                return ResourceManager.GetString("CircuitDrawingCreditArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/ReffiComics.
        /// </summary>
        public static string CircuitDrawingCreditLink {
            get {
                return ResourceManager.GetString("CircuitDrawingCreditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximamente....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créditos.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dibujo por:.
        /// </summary>
        public static string DrawingBy {
            get {
                return ResourceManager.GetString("DrawingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting, frameworks y liberías.
        /// </summary>
        public static string FrameworkCredits {
            get {
                return ResourceManager.GetString("FrameworkCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/vichoste.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Fonts.
        /// </summary>
        public static string GoogleFonts {
            get {
                return ResourceManager.GetString("GoogleFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fonts.google.com.
        /// </summary>
        public static string GoogleFontsLink {
            get {
                return ResourceManager.GetString("GoogleFontsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido a mi sitio web! Aquí podrás ver mis creaciones, logros y portafolio..
        /// </summary>
        public static string IndexCardSubtitle {
            get {
                return ResourceManager.GetString("IndexCardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola! Me llamo Vicente Calderón :D.
        /// </summary>
        public static string IndexCardTitle {
            get {
                return ResourceManager.GetString("IndexCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/vichoste_tcb.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encontrado.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que aquí no hay nada....
        /// </summary>
        public static string NotFoundCaption {
            get {
                return ResourceManager.GetString("NotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vicho&apos;s Personal Website.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tiktok.com/@vichoste.
        /// </summary>
        public static string TikTok {
            get {
                return ResourceManager.GetString("TikTok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/vichoste.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vicente Calderón.
        /// </summary>
        public static string Vicente {
            get {
                return ResourceManager.GetString("Vicente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vichoste.
        /// </summary>
        public static string Vichoste {
            get {
                return ResourceManager.GetString("Vichoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/user/vichoste.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
